version: 2

models:
  - name: hub_customer
  - name: hub_product
  - name: hub_purchase
  - name: link_customer_purchase
  - name: link_purchase_product
  - name: sat_customer_details
  - name: sat_purchase_details
  - name: sat_product_details
  - name: sat_customer_crm_details
  - name: sat_product_price